### ISSUE TITLE
Call to deprecated function format_username

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/nodeaccess_userreference#1]
Get error with Drupal compatibility disabled:

```
Error: Call to undefined function format_username() in nodeaccess_userreference_form_field_ui_field_edit_form_alter() (line 129 of /app/docroot/modules/nodeaccess_userreference/nodeaccess_userreference.module).[Dismiss](https://scissor-grid.lndo.site/admin/structure/types/manage/person/fields/field_person_user?destinations%5B0%5D=admin/structure/types/manage/person/fields#)Call to undefined function format_username()
```

Should be user_format_name() instead.  PR to follow.

**Comment by indigoxela** [comment]
I can confirm, that the module breaks the site, when the compatibility layer's off.

When visiting the field setting of an entityreference field, like `admin/structure/types/manage/NODETYPE/fields/MYFIELD` I get:
```
Error: Call to undefined function format_username() in nodeaccess_userreference_form_field_ui_field_edit_form_alter() (Zeile 129 von .../modules/nodeaccess_userreference/nodeaccess_userreference.module).
```
I can also confirm, that the PR fixes it. :+1: 

Maybe we should ping @herbdool, who might not be aware of this fix and that he's maintainer of this module. :wink:

**Comment by herbdool** [comment]
Nope, I wasn't aware. But I will always look at pings. I'll take a look.
